version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: altaclp-postgres
    restart: always
    environment:
      POSTGRES_USER: altaclp
      POSTGRES_PASSWORD: altaclp123
      POSTGRES_DB: altaclp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
